name: Deploying Springboot Packag(war) to tomcat on Windows Server

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Springboot App
    runs-on: ubuntu-latest
    steps:
      - name: Download the Source Code
        uses: actions/checkout@v3
      
      - name: Setup the Java 17
        uses:  actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify the Java Version
        run: java --version

      - name: Make mvnw Exectuable
        run: chmod +x mvnw*

      - name: Build the Application
        run: ./mvnw package
      
      - name: Verify the War file is created or not
        run: ls -l ./target/

      - name: Rename the Long File name to Short File
        run: |
          cd target
          mv CustomerService-0.0.1-SNAPSHOT.war CS.war

      # - name: verify CATALINA is configured or not
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USER }}
      #     password: ${{ secrets.PASSWORD }}
      #     script: |
      #       echo %CATALINA_HOME%

      - name: Copy the CS.War file to C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          local: './target/CS.war'
          remote: 'C:\Program Files\Apache Software Foundation\Tomcat 10.1\webapps\'
          host: ${{secrets.HOST}}
          user: ${{secrets.USER}}
          password: ${{secrets.PASSWORD}}
          ssh_options: -o StrictHostKeyChecking=no
          pre_upload: net stop Tomcat10 && rmdir /s /q "C:\Program Files\Apache Software Foundation\Tomcat 10.1\webapps\CS"
          post_upload: net start Tomcat10

      
